version: '2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - http_proxy
      - https_proxy
      - CLUSTER_NAME=ezmesure
      - EZMESURE_ES_PUBLISH
      - EZMESURE_ES_NODE_NAME
      - EZMESURE_ES_DISCOVERY
      - EZMESURE_ES_NODE_MASTER
      - EZMESURE_ES_NODE_DATA
      - EZMESURE_ES_NODE_INGEST
      - EZMESURE_ES_NODE_SEARCH_REMOTE
      - EZMESURE_ES_MINMASTER
      - EZMESURE_SMTP_HOST
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: ${EZMESURE_ES_MEM_LIMIT}

    volumes:
      - "./data/elastic/data:/usr/share/elasticsearch/data"
      - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
#      - "./elasticsearch/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties"
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.2
    ports:
      - 5601:5601
    links:
      - elastic
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - ELASTICSEARCH_PASSWORD
      - SERVER_BASEPATH
      - SERVER_HOST
      - SERVER_PORT
      - ELASTICSEARCH_URL
      - XPACK_MONITORING_ENABLED
      - KIBANA_DEFAULTAPPID
      - EZMESURE_ES_REPORTING_HOSTNAME
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: unless-stopped

  mongodb:
    image: mongo:3.3.15
    volumes:
      - "./data/mongo:/data/db"
    command: --smallfiles
    restart: unless-stopped

  api:
    build:
      context: ./api
      args:
        - http_proxy
        - https_proxy
    ports:
      - 3000:3000
    environment:
      - http_proxy
      - https_proxy
      - EZMESURE_ELASTIC_HOST=elastic
      - EZMESURE_MONGO_HOST=mongodb
      - ELASTICSEARCH_PASSWORD
      - EZMESURE_AUTH_SECRET
      - EZMESURE_SMTP_HOST
      - EZMESURE_SMTP_PORT
      - NODE_ENV
    links:
      - elastic
      - mongodb
    volumes:
      - "./data/api/storage:/usr/src/app/storage"
    restart: unless-stopped

  front:
    build:
      context: ./front
      args:
        - http_proxy
        - https_proxy
    ports:
      - 8080:8080
    environment:
      - EZMESURE_API_URL=/api
      - PORT=8080
      - HOST=0.0.0.0
    restart: unless-stopped

  rp:
    build:
      context: ./rp
      args:
        - http_proxy
        - https_proxy
    ports:
      - 443:443
    environment:
      - http_proxy
      - https_proxy
      - APPLI_APACHE_SERVERNAME
      - APPLI_APACHE_SERVERADMIN
      - APPLI_APACHE_LOGLEVEL
    working_dir: /var/www/html
    volumes:
      - ./rp/shibboleth:/etc/shibboleth
      - ./rp/shibboleth/ssl:/etc/shibboleth/ssl
      - ./rp/apache2/sites-available:/etc/apache2/sites-available
      - ./rp/sp-log/:/var/log/shibboleth/
    restart: unless-stopped
