version: '2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.0.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - http_proxy
      - https_proxy
      - CLUSTER_NAME=ezmesure
    volumes:
      - "./data/elastic/data:/usr/share/elasticsearch/data"
      - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    restart: unless-stopped

  kibana:
    build:
      context: ./kibana
      args:
        - http_proxy
        - https_proxy
    links:
      - elastic
    environment:
      - http_proxy
      - https_proxy
      - SERVER_BASEPATH=/kibana
      - ELASTICSEARCH_URL=http://elastic:9200
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: unless-stopped

  jwtproxy:
    build:
      context: ./jwt-rp
      args:
        - http_proxy
        - https_proxy
    ports:
      - 5601:3030
    environment:
      - http_proxy
      - https_proxy
      - TARGET_URL=http://kibana:5601
      - JWT_SECRET=${EZMESURE_AUTH_SECRET}
    links:
      - kibana
    restart: unless-stopped

  mongodb:
    image: mongo:3.3.15
    volumes:
      - "./data/mongo:/data/db"
    command: --smallfiles
    restart: unless-stopped

  api:
    build:
      context: ./api
      args:
        - http_proxy
        - https_proxy
    ports:
      - 3000:3000
    environment:
      - http_proxy
      - https_proxy
      - EZMESURE_ELASTIC_HOST=elastic
      - EZMESURE_MONGO_HOST=mongodb
      - EZMESURE_AUTH_SECRET
      - NODE_ENV
    links:
      - elastic
      - mongodb
    restart: unless-stopped

  front:
    build:
      context: ./front
      args:
        - http_proxy
        - https_proxy
    ports:
      - 8080:8080
    environment:
      - EZMESURE_API_URL=/api
    restart: unless-stopped

  rp:
    build:
      context: ./rp
      args:
        - http_proxy
        - https_proxy
    ports:
      - 443:443
    environment:
      - http_proxy
      - https_proxy
      - APPLI_APACHE_SERVERNAME
      - APPLI_APACHE_SERVERADMIN
      - APPLI_APACHE_LOGLEVEL
    working_dir: /var/www/html
    volumes:
      - ./rp/shibboleth:/etc/shibboleth
      - ./rp/shibboleth/ssl:/etc/shibboleth/ssl
      - ./rp/apache2/sites-available:/etc/apache2/sites-available
      - ./rp/sp-log/:/var/log/shibboleth/
    restart: unless-stopped
