version: '2'
services:
  elastic:
    extends:
      file: docker-compose.yml
      service: elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.2
    ports:
      - 5601:5601
    links:
      - elastic
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - ELASTICSEARCH_PASSWORD
      - SERVER_BASEPATH
      - SERVER_HOST
      - SERVER_PORT
      - ELASTICSEARCH_URL
      - XPACK_MONITORING_ENABLED
      - KIBANA_DEFAULTAPPID
      - EZMESURE_ES_REPORTING_HOSTNAME
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: unless-stopped

  mongodb:
    extends:
      file: docker-compose.yml
      service: mongodb

  rp:
    extends:
      file: docker-compose.yml
      service: rp

  api:
    image: node:8.5.0-wheezy
    ports:
      - 3000:3000
    volumes:
      - "./api:/usr/src/app"
      - "./data/api/storage:/usr/src/app/storage"
    working_dir: /usr/src/app
    environment:
      - http_proxy
      - https_proxy
      - EZMESURE_ELASTIC_HOST=elastic
      - EZMESURE_MONGO_HOST=mongodb
      - ELASTICSEARCH_PASSWORD
      - EZMESURE_AUTH_SECRET
      - EZMESURE_SMTP_HOST=maildev
      - EZMESURE_SMTP_PORT=25
      - EZMESURE_GOOGLE_EMAIL
      - EZMESURE_GOOGLE_PRIVATE_KEY
      - EZMESURE_NOTIFICATIONS_SENDER
      - EZMESURE_NOTIFICATIONS_CRON
      - EZMESURE_NOTIFICATIONS_RECIPIENTS
      - NODE_ENV
    links:
      - elastic
      - mongodb
      - maildev
    restart: "no"
    command: npm run dev

  front:
    image: node:8.5.0-wheezy
    ports:
      - 8080:8080
    volumes:
      - "./front:/usr/src/app"
    working_dir: /usr/src/app
    environment:
      - EZMESURE_API_URL=/api
      - HOST=0.0.0.0
      - PORT=8080
    command: npm run dev
    restart: "no"

  maildev:
    image: djfarrelly/maildev
    ports:
      - 1080:80
